name: 亦执
markdown: kramdown
kramdown:
  toc_levels: 2..3
#   input: kramdown
hilighter: "rouge"
timezone: Asia/Chongqing

# destination: public
exclude: ["CNAME", "public", "README.md"]

permalink: /blog/:categories/:title/

url: http://blog.fanyange.com

navigation:
  - blog
  - wiki
  - about

elsewhere:
  - name: Douban
    link: http://www.douban.com/people/fanyange/
  - name: Weibo
    link: http://weibo.com/fanyange
  - name: Motto
    link: /motto

# disqus: yizhi
duoshuo: yizhi-fanyange


author: Tom Mao

engine:
  name: Jekyll
  link: http://jekyllrb.com/
  author: 
    name: Tom Preston-Werner
    link: http://tom.preston-werner.com/

defaults:
  -
    scope:
      path: "wiki" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "wiki"
